<?php
namespace Jamrock\Controllers;

use WP_REST_Request;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class PaymentExtension {


	public function hooks(): void {
		add_action( 'rest_api_init', array( $this, 'routes' ) );
	}

	public function routes(): void {
		register_rest_route(
			'jamrock/v1',
			'/payment-extensions/(?P<id>\d+)',
			array(
				'methods'             => 'GET',
				'callback'            => array( $this, 'getExtension' ),
				'permission_callback' => function () {
					return is_user_logged_in(); },
			)
		);

		register_rest_route(
			'jamrock/v1',
			'/payment-extensions/find',
			array(
				'methods'             => 'GET',
				'callback'            => array( $this, 'findByApplicant' ),
				'permission_callback' => function () {
					return is_user_logged_in(); },
			)
		);

		register_rest_route(
			'jamrock/v1',
			'/payment-extensions/(?P<id>\d+)/submit',
			array(
				'methods'             => 'POST',
				'callback'            => array( $this, 'submit_signature' ),
				'permission_callback' => function () {
					return is_user_logged_in(); },
			)
		);

		register_rest_route(
			'jamrock/v1',
			'/payment-extensions/(?P<id>\d+)/status',
			array(
				'methods' => 'POST',
				'callback' => array($this, 'update_status'),
				'permission_callback' => function () {
					return is_user_logged_in();
				},
			)
		);
	}

	public function getExtension( WP_REST_Request $req ) {
		global $wpdb;
		$tbl = $wpdb->prefix . 'jamrock_housing_applications';
		$id  = intval( $req->get_param( 'id' ) );
		$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$tbl} WHERE id=%d", $id ), ARRAY_A );
		if ( ! $row ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'not_found',
				),
				404
			);
		}

		// decode json fields if stored as strings
		if ( ! empty( $row['payment_extension'] ) && is_string( $row['payment_extension'] ) ) {
			$row['payment_extension'] = json_decode( $row['payment_extension'], true );
		}
		if ( ! empty( $row['fields_json'] ) && is_string( $row['fields_json'] ) ) {
			$row['fields_json'] = json_decode( $row['fields_json'], true );
		}
		return rest_ensure_response(
			array(
				'ok'   => true,
				'item' => $row,
			)
		);
	}

	public function findByApplicant( WP_REST_Request $req ) {
		global $wpdb;
		$tbl          = $wpdb->prefix . 'jamrock_housing_applications';
		$applicant_id = intval( $req->get_param( 'applicant_id' ) );
		if ( ! $applicant_id ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'invalid_applicant',
				),
				400
			);
		}
		$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$tbl} WHERE applicant_id=%d", $applicant_id ), ARRAY_A );
		if ( ! $row ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'not_found',
				),
				404
			);
		}
		if ( ! empty( $row['payment_extension'] ) && is_string( $row['payment_extension'] ) ) {
			$row['payment_extension'] = json_decode( $row['payment_extension'], true );
		}
		return rest_ensure_response(
			array(
				'ok'   => true,
				'item' => $row,
			)
		);
	}

	/**
	 * Accepts filled_pdf (file) from client (pdf-lib filled + signature embedded).
	 * Saves to uploads and updates payment_extension JSON with final_signed_pdf
	 */
	public function submit_signature( WP_REST_Request $req ) {
		global $wpdb;
		$tbl = $wpdb->prefix . 'jamrock_housing_applications';

		$id = intval( $req->get_param( 'id' ) );
		if ( ! $id ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'invalid_id',
				),
				400
			);
		}

		$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$tbl} WHERE id=%d", $id ), ARRAY_A );
		if ( ! $row ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'not_found',
				),
				404
			);
		}

		$user = wp_get_current_user();
		if ( intval( $row['applicant_id'] ) !== intval( $user->ID ) && ! current_user_can( 'edit_others_posts' ) ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'forbidden',
				),
				403
			);
		}

		// get uploaded files
		$files = $req->get_file_params();

		// Expecting 'filled_pdf' file (generated by client)
		if ( empty( $files ) || empty( $files['filled_pdf'] ) || empty( $files['filled_pdf']['tmp_name'] ) ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'no_filled_pdf',
				),
				400
			);
		}

		$tmp = $files['filled_pdf']['tmp_name'];
		if ( ! is_readable( $tmp ) ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'filled_pdf_not_readable',
				),
				400
			);
		}

		// Save file to uploads
		require_once ABSPATH . 'wp-admin/includes/file.php';
		$uploads = wp_upload_dir();
		if ( empty( $uploads ) || empty( $uploads['basedir'] ) ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'upload_dir_error',
				),
				500
			);
		}

		$fname = 'payment_extension_signed_' . $id . '_' . time() . '.pdf';
		$dest  = trailingslashit( $uploads['basedir'] ) . $fname;

		// move tmp to uploads (try move_uploaded_file, then copy)
		$moved = false;
		if ( @is_uploaded_file( $tmp ) ) {
			$moved = @move_uploaded_file( $tmp, $dest );
		}
		if ( ! $moved ) {
			$moved = @copy( $tmp, $dest );
		}
		if ( ! $moved ) {
			// fallback to wp_handle_upload
			$handled = wp_handle_upload( $files['filled_pdf'], array( 'test_form' => false ) );
			if ( ! empty( $handled['file'] ) ) {
				$dest  = $handled['file'];
				$moved = true;
				$fname = basename( $dest );
			}
		}
		if ( ! $moved ) {
			return rest_ensure_response(
				array(
					'ok'    => false,
					'error' => 'save_failed',
				),
				500
			);
		}

		$signed_url = trailingslashit( $uploads['baseurl'] ) . $fname;

		// also optional: if client sent individual signature image, save it (not required)
		if ( ! empty( $files['signature'] ) && ! empty( $files['signature']['tmp_name'] ) ) {
			$sig_tmp  = $files['signature']['tmp_name'];
			$sig_info = wp_check_filetype_and_ext( $sig_tmp, $files['signature']['name'] );
			$sig_ext  = $sig_info['ext'] ?? 'png';
			$sig_name = 'payment_ext_signature_' . $id . '_' . time() . '.' . $sig_ext;
			$sig_dest = trailingslashit( $uploads['basedir'] ) . $sig_name;
			if ( @is_uploaded_file( $sig_tmp ) ) {
				@move_uploaded_file( $sig_tmp, $sig_dest );
			} else {
				@copy( $sig_tmp, $sig_dest );
			}
		}

		// Update DB: merge into existing payment_extension JSON
		$cur    = $row['payment_extension'];
		$curArr = array();
		if ( $cur && is_string( $cur ) ) {
			$tmp = json_decode( $cur, true );
			if ( is_array( $tmp ) ) {
				$curArr = $tmp;
			}
		} elseif ( is_array( $cur ) ) {
			$curArr = $cur;
		}

		$curArr['status']           = 'submitted';
		$curArr['final_signed_pdf'] = $signed_url;
		$curArr['signed_at']        = current_time( 'mysql' );

		$wpdb->update(
			$tbl,
			array(
				'payment_extension' => wp_json_encode( $curArr ),
				'signed_pdf_url'    => $signed_url,
				'status'            => 'pending',
				'updated_at'        => current_time( 'mysql' ),
			),
			array( 'id' => $id ),
			array( '%s', '%s', '%s', '%s' ),
			array( '%d' )
		);

		return rest_ensure_response(
			array(
				'ok'             => true,
				'signed_pdf_url' => $signed_url,
			)
		);
	}

	/**
	 * Summary of update_status
	 * @param \WP_REST_Request $req
	 * @return \WP_REST_Response|\WP_Error
	 */
	public function update_status( WP_REST_Request $req ) {
		global $wpdb;
		$tbl = $wpdb->prefix . 'jamrock_housing_applications';

		$id = intval($req->get_param('id'));
		$status = sanitize_text_field($req->get_param('status'));


		if (!in_array($status, array('approved', 'rejected'), true)) {
			return new \WP_Error('invalid_status', 'Status must be approved or rejected', array('status' => 400));
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		$updated = $wpdb->update(
			$tbl,
			array(
				'payment_extension_status' => $status,
				'updated_at' => current_time('mysql'),
			),
			array('id' => $id)
		);

		if (false === $updated) {
			return new \WP_Error('db_error', 'Update failed', array('status' => 500));
		}

		return rest_ensure_response(array('ok' => true));
	}
}
